### ISSUE TITLE
Only me (the host) sees proper map

### ISSUE THREAD

**Issue by educatedbulldog** [TofuBytesDEV/TelamonMoon#11]
For some reason only i am able to see any loot and we load into different maps. I am the host and they load into seperate interiors with no loot. On my screen they are walking in the void.

**Comment by TofuBytesDEV** [comment]
Hmm... Yes I also had this issue where some friends (the host) saw scraps appearing in areas that weren't on my end. This is very likely to do with LethalExpansion/LethalExpansionCore and is more so other custom moons as well...

All I can suggest is to report this to the respective developer of whichever mod is installed with my moon: LethalExpansion or LethalExpansionCore.

I, of course, hope to update this ticket when they resolve the issue. :) Thanks for letting me know!
